### ISSUE TITLE
GroupNorm crashes on x10

### ISSUE THREAD

**Issue by s1ddok** [tensorflow/swift-apis#1031]
I've [tried to fix it](https://github.com/tensorflow/swift-apis/pull/1030), but it didn't work. I believe this is because eps is initialized on TFEager instead of x10 by default. Should tensor's scalar inits accept device as well?

**Comment by BradLarson** [comment]
I believe this should be fixed in PR #1042, which I forgot to pull in yesterday but should show up in tonight's nightly builds. I tested it locally, and it seemed to allow GroupNorm and LayerNorm to work well with X10 in simple models.

Your original fix may not have worked due to the creation of the eager-mode tensor, followed by the copy. `Tensor(self.epsilon, deviceAndPrecisionLike: $0)` created a scalar Tensor directly on device, which is what I think you were looking for. Wrapping that in `withoutDerivative(at:)` further prevents scalarizing the epsilon value in the backward pass, which we know from unfortunate experience will really slow down X10, so I think this approach should be compatible and fast.

If this doesn't fix the issue once it's in the toolchain, let me know and I can take a deeper look into it.

**Comment by BradLarson** [comment]
I'm assuming that this has been fixed, but if it still occurs in your tests, feel free to reopen this issue.
