### ISSUE TITLE
Bug when using .concatenated

### ISSUE THREAD

**Issue by kongzii** [tensorflow/swift-apis#1087]
While developing https://github.com/tensorflow/swift-apis/pull/946 I found out a bug when using Tensor.concatenated method.

Here is the code to reproduce the error in swift colab: https://colab.research.google.com/drive/11fZldGxz1O5LUfoT2WhzusuPQFyA4HdX?usp=sharing

If you use the mode "concat", it will fail on:

`Precondition failed: Axis must be in `-rank..<rank` when calling split(sizes:alongAxis:) (rank: 0, axis: -1): file /swift-base/tensorflow-swift-apis/Sources/TensorFlow/Operators/Basic.swift, line 142`

If you switch to "sum" mode, output will be:

```
30.0
[[[1.0, 1.0, 1.0]], 0.0, [[1.0, 1.0, 1.0]]]
```

And here is the Python version: https://colab.research.google.com/drive/1joRHIfFOSmRVWC3kLii4sY31vya1sdGx?usp=sharing

In Python, both "concat" and "sum" produces the output:

```
tf.Tensor(30.0, shape=(), dtype=float32)
[[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>, None, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>]]
```

**Comment by xihui-wu** [comment]
The reason is that when it's trying to compute derivatives of 'concatenated' for first values.count - 1 elements of 'values', the back-propagated derivatives are scalar zeros. Ideally they should be zero tensors in the desired shape. We are working on a longer-term fix here https://bugs.swift.org/browse/TF-1005. But for now I'd recommend this workaround. In your func test, if mode == 'concat' do this:

if mode == "concat" {
    let concat = inputs[index].concatenated(with: inputs[reversedIndex], alongAxis: -1)
    values.append(concat.withDerivative { [shape = concat.shape] in
        if $0 == Tensor(0) { $0 = Tensor(zeros: shape) }
    })
}

**Comment by saeta** [comment]
Closing this issue as TF-1005 is the underlying fix, and the above workaround should work. Thanks @xihui-wu  and @kongzii !
