### ISSUE TITLE
What's the expected output from Device.allDevices ?

### ISSUE THREAD

**Issue by xihui-wu** [tensorflow/swift-apis#1089]
I ran this on colab with CPU, GPT and TPU respectively. Here are their outputs:

CPU:
1 element
  ▿ 0 : Device(kind: .CPU, ordinal: 0, backend: .XLA)
    - kind : TensorFlow.Device.Kind.CPU
    - ordinal : 0
    - backend : TensorFlow.Device.Backend.XLA

GPU:
1 element
  ▿ 0 : Device(kind: .GPU, ordinal: 0, backend: .XLA)
    - kind : TensorFlow.Device.Kind.GPU
    - ordinal : 0
    - backend : TensorFlow.Device.Backend.XLA

TPU:
9 elements
  ▿ 0 : Device(kind: .CPU, ordinal: 0, backend: .XLA)
    - kind : TensorFlow.Device.Kind.CPU
    - ordinal : 0
    - backend : TensorFlow.Device.Backend.XLA
  ▿ 1 : Device(kind: .TPU, ordinal: 0, backend: .XLA)
    - kind : TensorFlow.Device.Kind.TPU
    - ordinal : 0
    - backend : TensorFlow.Device.Backend.XLA
  ▿ 2 : Device(kind: .TPU, ordinal: 1, backend: .XLA)
    - kind : TensorFlow.Device.Kind.TPU
    - ordinal : 1
    - backend : TensorFlow.Device.Backend.XLA
  ...
  ▿ 8 : Device(kind: .TPU, ordinal: 7, backend: .XLA)
    - kind : TensorFlow.Device.Kind.TPU
    - ordinal : 7
    - backend : TensorFlow.Device.Backend.XLA

My confusion is why GPU output doesn't contain CPU device but that of TPU does ? What are expected ?

**Comment by brettkoonce** [comment]
see also https://github.com/tensorflow/swift/issues/524

**Comment by BradLarson** [comment]
This is due to the cause behind issue #1059, in that the X10 backend searches out and automatically exposes the best accelerator it finds on CPU / GPU systems. In doing so, it doesn't expose the other devices on the system, including the CPU on a CPU + GPU system, or additional GPUs or CPUs beyond the first.

This can be done manually at the command line by constructing the kind of environment variable string I list in #1059, but the proper mappings should be detected and taken care of for you internally. I believe that's the focus of that other issue, and it's being worked on in parallel to the visibility issues with the eager-mode devices.

**Comment by marcrasi** [comment]
@xihui-wu will verify and close after #1059 is fixed.

**Comment by xihui-wu** [comment]
Verified this issue is gone.
