### ISSUE TITLE
Learning with GPU docs

### ISSUE THREAD

**Issue by kefirski** [tensorflow/swift-apis#204]
It's unclear how does GPU/TPU support work in swift for tensorflow. I haven't found any docs on this topic.

In PyTorch I am able to cast some tensor from cpu to gpu by calling special method `.to(device)` like` x.to(t.device("cuda:2"))` in order to cast `x` to gpu with id equal to `2`.

How does this work in swift for tf? I noticed that I could change env variable in collab from `None` to `GPU` and all computations would be performed on GPU, but it's still unclear how could I do something like that using compiler.

I believe that learning models with GPU/GPUs is very important part of deep learning pipeline and thus it have to be in docs in any form.

**Comment by rxwei** [comment]
Currently, device placement in Swift for TensorFlow (and TensorFlow in general) is per-operation, not per-tensor. You can use the [`withDevice(_:_:perform:)`](https://www.tensorflow.org/swift/api_docs/Functions#/s:10TensorFlow10withDevice__7performxAA0D4KindO_SuxyKXEtKlF) API (implemented [here](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Core/Execution.swift#L32)) to switch between devices. You can switch between CPU and GPU for parts of your program using this API. If you have installed a CUDA-enabled toolchain on Linux and already have a GPU installed, the default device should already be the GPU.

While the device placement API is available in API documentation, it is true that it's not documented in any of our tutorials. That is because device placement is still an experimental feature that does not yet work reliably. For instance, the [`tpu` case](https://github.com/tensorflow/swift-apis/blob/8eae84544c4b51474b35f27a7c45f6211e63e10c/Sources/TensorFlow/Core/Execution.swift#L22) in the `DeviceKind` enum is not supported yet. We plan to add tutorials once the feature becomes more ready and reliable.
