### ISSUE TITLE
Layers without biases - optional weights

### ISSUE THREAD

**Issue by tanmayb123** [tensorflow/swift-apis#38]
Currently the `Dense` layer *must* have a bias - there should be a way for the user to specify whether or not they want that bias value. Will something along these lines be possible eventually? https://gist.github.com/tanmayb123/f3631d283cb763ccc30447869efe13e8

Because for now, I think I'd need to something along these lines: https://gist.github.com/tanmayb123/0fd2a935dacb9e012174035ba4aed25f (this compiles successfully)

The second solution isn't very elegant, though.

**Comment by rxwei** [comment]
I think both weights and activation should be optional, but just as you've tried, it requires manual branches because automatic differentiation does not support control flow yet. I'm actually fine with checking in the change with custom VJP. Control flow support will be implemented in the next two months.

**Comment by rxwei** [comment]
had a typo, bias :)

**Comment by tanmayb123** [comment]
Control flow support would be really useful here, but just one more question: Will optional variables be `Differentiable`? Could `bias` just be an optional variable, with an `if let` statement once control flow is implemented?

**Comment by rxwei** [comment]
Optionals can be made differentiable via a conditional conformance.
```swift
extension Optional : Differentiable where Wrapped : Differentiable { ... }
```

**Comment by tanmayb123** [comment]
Oh, even better. Shouldn't this be the case by default, though?

**Comment by rxwei** [comment]
That should be added to the standard library.

**Comment by BradLarson** [comment]
Optional differentiation may still [be in progress](https://bugs.swift.org/browse/SR-13700), but in the time since this issue was raised we've implemented workarounds for the relevant layers that allow you to avoid providing a bias to many of them. In practice, this has addressed the core needs brought up here, so I'll close this out.
