### ISSUE TITLE
Any guidance on how to implement custom operations with x10?

### ISSUE THREAD

**Issue by s1ddok** [tensorflow/swift-apis#813]
Is there a minimal example on how one can introduce a custom layer for shiny new x10 backend? I know we can enforce lazy tensor barrier, do whatever we want with tensor's memory and then schedule other x10 operations, but that will introduce performance hiccups because CPU/GPU sync and memory transfer. I'm looking for a way to be able to write arbitrary logic that would be compiled and run within the same pass with other built-in ops. 

I would appreciate any help on this!

*Edit:* In case it might help by bringing a little context: I'm trying to implement a learnable look-up table. From what I can see it is not possible to implement any sampling operations using a composition of current ops in `swift-api`.

**Comment by asuhan** [comment]
Thank you for the question!

As long as what you're trying to implement can be expressed in terms of XLA operations as described by https://www.tensorflow.org/xla/operation_semantics, it's possible. We just need to expose them as tensor methods, like we did for several operations already (check https://github.com/tensorflow/swift-apis/blob/master/Sources/x10/xla_tensor/ops/xla_avg_pool.h for example).

**Comment by s1ddok** [comment]
@asuhan thank's for such a quick answer. I will examine this one! Am I correct all those things have to be implemented in C++? Can one create custom ops for XLA? I want to implement some learnable pixel-level operators mostly based on sampling (like LUT, warping etc) but completely lost on where to start

**Comment by s1ddok** [comment]
Will XLA custom calls headers be exposed? 

Like the ones stated in their tutorial

```
#include "tensorflow/compiler/xla/client/xla_builder.h"
#include "tensorflow/compiler/xla/service/custom_call_target_registry.h"
```

**Comment by asuhan** [comment]
@s1ddok Currently they have to be manually implemented in XLA, but they're very simple wrappers over the XLA builder interface. They're simple enough that we plan to auto-generate them in the future, all the way to Swift.

Creating a completely custom operator is possible, but it'd require writing CUDA C++ (or C++, for CPU). We already use eager TF kernels running on CPU for a handful of operations which can't be expressed well in XLA. We haven't documented that in detail, but it's basically using copy to device operations to transfer the operands to CPU memory and the result back to the device. You can get a sense of how this is done by looking at https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Bindings/RawOpsDispatching.swift and https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Bindings/RawOpsGenerated.swift.

XLA itself offers a mechanism for custom calls (https://www.tensorflow.org/xla/custom_call), but it's quite similar in principle to what I've described and more difficult to deploy for our system.

Also, note that there's a performance penalty associated with doing such operators, since they'll break the trace into multiple, shorter traces and materialize intermediate results. Depending on how much you're leaning on custom operators vs regular ones, this might matter a lot or not at all.

**Comment by s1ddok** [comment]
@asuhan So basically even if you do custom CUDA stuff inside XLA custom calls that is basically the same as force tensor barrier and do whatever you want in user-space?

**Comment by asuhan** [comment]
@s1ddok Correct, on GPU and CPU at least. For TPU there's the additional aspect of shipping data over network (a very fast one, to be fair) because of 2-VM design, which an XLA `CustomCall` can avoid.

**Comment by s1ddok** [comment]
I think this answers my question fully. Thanks for such a quick response!

**Comment by saeta** [comment]
@asuhan My knowledge is definitely dated, but I thought on GPU that XLA custom calls didn't force the equivalent of a lazy tensor barrier, but could instead be folded into the program. Do you know if that's true? If so, it sounds like there might be a performance benefit if we could eventually figure out how to plumb through custom calls (bearing in mind that these would only work on {CPU|GPU} and not TPU, but that seems reasonable). Or alternatively, have this sort of capability fold into @pschuh 's ideas for blending in eager-mode?

**Comment by asuhan** [comment]
@saeta I can't imagine, conceptually, how could you fold CUDA C++ code into code generated by the XLA GPU backend. A custom call in XLA could avoid the overhead of an additional kernel launch, so it's not *strictly* the same thing. But, roughly speaking, we should be able to offer that functionality on our end without losing a lot of performance vs a custom call in XLA.

**Comment by asuhan** [comment]
@saeta Note how a custom GPU call is done in XLA: https://www.tensorflow.org/xla/custom_call#custom-call_on_gpu. It's essentially a CPU stub, which subsequently calls a GPU kernel, so it doesn't look it'd even save a kernel launch.
