### ISSUE TITLE
Long latency when allocating the first Tensor on GPUs

### ISSUE THREAD

**Issue by ematejska** [tensorflow/swift-apis#898]
Imported from JIRA https://bugs.swift.org/browse/TF-460

Type: | Bug | Priority: | Major
-- | -- | -- | --
Reporter: | Brennan Saeta | Assignee: | Unassigned
Resolution: | Unresolved | Votes: | 0
Labels: | None

The first time a Tensor is created when running on a machine with a GPU, there is a long pause. Subsequent tensor allocations are normal speed.

**Comment by BradLarson** [comment]
I'm pretty sure this was entirely due to what CUDA capabilities we were building into the TensorFlow side of things. A few months ago, we changed the capabilities to better align with what TensorFlow ships, which should provide the best coverage of CUDA devices without making the binary size of the toolchain too large. For devices with CUDA support, but without precompiled kernels in the shipped toolchain, they will experience a slight delay on first model execution due to just-in-time compilation of CUDA kernels for their hardware.

For posterity, we currently ship with support for CUDA compute capabilities 3.5, 3.7, 5.2, 6.0, 6.1, and 7.0 on CUDA 10.1 and 10.2, and 3.5, 5.0, 6.0, 7.0, 7.5, and 8.0 on CUDA 11.

If you consistently experience slow startup of models, it's possible that your CUDA cache isn't set high enough. This can be remedied via

```sh
export CUDA_CACHE_MAXSIZE=2147483647
```
