### ISSUE TITLE
Wrapper to enable recurrent cells to handle sequential input

### ISSUE THREAD

**Issue by tanmayb123** [tensorflow/swift-apis#91]
In Flux (machine learning for Julia) you can wrap an RNN Cell in a `Recur` type so it can keep track of the hidden state for you. Here's an example from their code:

```julia
accum(h, x) = (h+x, x)
rnn = Flux.Recur(accum, 0)
rnn(2) # 2
rnn(3) # 3
rnn.state # 5
rnn.(1:10) # apply to a sequence
rnn.state # 60
```

Would it be valuable to have something similar with swift-apis?

**Comment by rxwei** [comment]
Interesting. I think so. Would you like to prototype it?

**Comment by tanmayb123** [comment]
Sure thing, let's get the cells merged in first though.

**Comment by jekbradbury** [comment]
I'm not sure this API is as good a fit for Swift as it is for Julia--we've tended to avoid mutation here. Instead it might make sense to expose a `RNN<CellType>` layer that folds its underlying cell over an input array or tensor and returns an output array or tensor.

**Comment by tanmayb123** [comment]
Thanks for the suggestion James! I'll submit the PR for that soon.

**Comment by rxwei** [comment]
I think it's better to start prototyping a sequence-to-sequence layer that's generic over RNN cells once `Array` conforms to `Differentiable`, before trying layers that mutate internal states. For example:

```swift
struct RNN<Cell: RNNCell> {
    @differentiable
    func applied(to input: [Cell.Input]) -> Cell.Output {
        input.reduce(.zeroState) { ... }
    }
}
```

**Comment by rxwei** [comment]
`Array` now conforms to `Differentiable` thanks to work done by @eaplatanios and @marcrasi. We can go ahead and add an `RNN` layer now.

**Comment by tanmayb123** [comment]
Hooray! Should I also add the cells back with this PR? We can merge when TF-440 is resolved?

**Comment by rxwei** [comment]
It's already resolved and the cells are added back.

**Comment by tanmayb123** [comment]
Yeah just realized that sorry.

**Comment by tanmayb123** [comment]
Here's a quick sketch: https://gist.github.com/tanmayb123/33a337f5937cc588c2abc413b4e91343

**Comment by rxwei** [comment]
* It may be better to make `init` take a factory closure that creates a cell instead of a cell instance, because it may be confusing when `Cell` is a value type (that is, when the cell inside gets optimized but the cell you used to initialize the `RNN` doesn't).
* The use of `map(_:)` isn't quite right here, since `map(_:)` does not semantically guarantee the order. The right operator to use is `reduce(into:)`, or even just a bare for-loop.

**Comment by tanmayb123** [comment]
Alright I've made some updates: https://gist.github.com/tanmayb123/33a337f5937cc588c2abc413b4e91343

**Comment by lattner** [comment]
> Array now conforms to Differentiable thanks to work done by @eaplatanios and @marcrasi. We can go ahead and add an RNN layer now.

Amazing, great work!!!

**Comment by eaplatanios** [comment]
Given the current limitation of auto-diff for control flow, wouldn't it be better to delay adding an RNN that uses a for-loop until we can train it? Also, I believe there should be a discussion about how to implement RNNs so that they're efficient. The current approach in Python that uses TensorArrays is nice because it also allows parallelizing loops or parts of loops (e.g., in multi-layer RNNs). How could we achieve something similar in S4TF? This can actually have a significant performance impact for large models.

**Comment by tanmayb123** [comment]
In terms of the auto-diff control flow problem, we could just implement a custom VJP for now. (although waiting for the automatic version would be easier ;))

**Comment by rxwei** [comment]
It'd be nice to introduce multiple variations of `RNN` since it's not always necessary return all outputs. Keras [RNN](https://keras.io/layers/recurrent/) layer does this via flags, but we can do it more safely using types.
