### ISSUE TITLE
No such module 'TensorFlow'

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift-apis#949]
I added this repo (tensorflow / swift-apis) to my Xcode project and selected `DEVELOPMENT-SNAPSHOT-2020-05-08-a` snapshot toolchain from [swift.org](https://swift.org/download/#snapshots). 

I am unable to `import TensorFlow` in my project and building the project gives the error: `No such module 'TensorFlow'`.

Any solution? Does this repo does not work with 𝛁Swift?

**Comment by dan-zheng** [comment]
Hi Rahul,

[tensorflow/swift-apis](https://github.com/tensorflow/swift-apis) currently requires some apple/swift tensorflow branch specific features:
* [`KeyPathIterable` protocol and conformances.](https://github.com/apple/swift/blob/tensorflow/stdlib/public/core/KeyPathIterable.swift)
  * This is in the process of being moved to a separate Swift package.
* [`ElementaryFunctions` protocol and conformances.](https://github.com/apple/swift/blob/tensorflow/stdlib/public/core/MathFunctions.swift.gyb)
  * This is copied from [apple/swift-numerics](https://github.com/apple/swift-numerics/blob/master/Sources/RealModule/ElementaryFunctions.swift). Eventually, we should add apple/swift-numerics as a direct SwiftPM/CMake dependency instead of duplicating code.
* [`PointwiseMultiplicative` and `VectorProtocol` protocols and conformances.](https://github.com/apple/swift/blob/tensorflow/stdlib/public/Differentiation/DifferentiationSupport.swift)
  * These are new and ad-hoc. They exist to support machine learning optimizers. They are too ad-hoc to pitch to Swift Evolution or apple/swift-numerics, but we could ask for feedback.
* Derived conformances for all of the protocols above.

Thus, [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis) currently cannot be built via SwiftPM using swift.org toolchains built from apple/swift master branch. We care about eventually supporting this (and moving all development to master toolchains), but we don't have a concrete roadmap yet since it's not clear how to support some of the above changes on master branch.

We can share updates when we start making progress in this direction!

**Comment by dan-zheng** [comment]
For now, you can only build [tensorflow/swift-apis](https://github.com/tensorflow/swift-apis) with toolchains built from [apple/swift tensorflow branch](https://github.com/apple/swift/tree/tensorflow), available [here](https://github.com/tensorflow/swift/blob/master/Installation.md).

**Comment by rahulbhalley** [comment]
Got it, thanks!
